### ISSUE TITLE
Remove "st", "nd", "rd" and "th" in translations

### ISSUE THREAD

**Issue by Eloitor** [williamtroup/Calendar.js#231]
**Describe the bug**
Some translations shouldn't use "st", "nd", "rd" and "th" in the numbers of the days.

**To Reproduce**
1. Go to https://calendar-js.com/examples/translations.html
4. See "st", "nd", "rd" and "th" in the numbers of the days.

**Expected behavior**
Day numbers should be "1", "2", "3", ... without "st", "nd", "rd" and "th".

**Comment by williamtroup** [comment]
Which translation file is this for?

**Comment by Eloitor** [comment]
spanish ant catalan at least.

**Comment by williamtroup** [comment]
Fixed and released in v2.10.16.

**Comment by Eloitor** [comment]
After updating it still shows "st", "nd", "rd", and "th"...

![imatge](https://github.com/williamtroup/Calendar.js/assets/17795572/f89fc5bc-861e-4447-b707-2910e2cfe276)

**Comment by williamtroup** [comment]
Yes, I've discovered a small issue.  Will get this fixed and issued in the next release.

**Comment by williamtroup** [comment]
I've just released v2.10.17 which fixes this issue, and fixes issues around other empty strings being used.
